Starts adding support for --max-warnings flag in lint command
intuit/design-systems-cli pull request #485
Opened 2020-09-11 17:20 UTC by athityakumar

# What Changed

Support for `--max-warnings` flag for the `lint` command has been added, as per feature request #200.

# Why

Todo:

- [ ] Add tests
- [ ] Add docs

2020-09-11 17:22 UTC, athityakumar commented on plugins/lint/src/utils/lintUtils.ts
> +  const returnCode = (report.errorCount > 0 || report.warningCount > maxWarnings) ? 1 : 0;
As mentioned in https://github.com/eslint/eslint/issues/4125#issuecomment-147839509, the `--max-warnings` functionality isn't handled by `CLIEngine` itself, rather by the `cli.js` by just looking at the total number of warnings and comparing it to the max warnings.

2020-09-11 19:14 UTC, hipstersmoothie requested changes
Fix the lint and this looks good to go!

2020-09-11 19:14 UTC, hipstersmoothie commented on plugins/lint/src/utils/lintUtils.ts
> +  return returnCode;
just return the above line since the variable is only used once

2020-09-12 14:20 UTC, athityakumar commented
@hipstersmoothie - Looks like an "auto"-friendly semver label has to be added to the PR, for the final `ci/pr-check` step to also pass. I don't have access to add a label to this PR 😅

2020-09-14 17:18 UTC, merged

2020-09-14 17:29 UTC, hipstersmoothie commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v2.1.0`](https://github.com/intuit/design-systems-cli/releases/tag/v2.1.0) :rocket: